import json
import resend
from app.config import get_settings

settings = get_settings()


async def send_brief_email(to_email: str, user_name: str, brief_content: str) -> None:
    """Send the daily brief via email using Resend."""
    resend.api_key = settings.resend_api_key

    brief = json.loads(brief_content)

    html = f"""
    <h2>Good Morning {user_name},</h2>
    <h3>Summary</h3>
    <p>{brief.get('summary', '')}</p>

    <h3>Priorities</h3>
    <ul>{''.join(f'<li>{p}</li>' for p in brief.get('priorities', []))}</ul>

    <h3>Focus Areas</h3>
    <ul>{''.join(f'<li>{f}</li>' for f in brief.get('focus_areas', []))}</ul>

    <h3>Risks</h3>
    <ul>{''.join(f'<li>{r}</li>' for r in brief.get('risks', []))}</ul>

    <h3>Follow-Ups</h3>
    <ul>{''.join(f'<li>{f}</li>' for f in brief.get('follow_ups', []))}</ul>

    <hr>
    <p><em>Generated by ChiefOS - Your AI Chief of Staff</em></p>
    """

    resend.Emails.send(
        {
            "from": settings.from_email,
            "to": [to_email],
            "subject": f"Your Daily Brief - {user_name}",
            "html": html,
        }
    )
