"""add_archived_columns

Revision ID: 01b5868ea647
Revises: 1bb61f0d9e27
Create Date: 2026-06-23 17:28:09.511258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b5868ea647'
down_revision: Union[str, None] = '1bb61f0d9e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('emails', sa.Column('archived', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'archived')
    op.drop_column('calendar_events', 'archived')
    # ### end Alembic commands ###
